version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running unit tests"
      - pytest

  build:
    commands:
      - echo "Deploying to AWS Bedrock / SageMaker endpoint"
      - python infrastructure/deploy_bedrock_endpoint.py

artifacts:
  files:
    - "**/*"
